# -*- coding: utf-8 -*-
"""geospatial analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FfAhPnCGuWY0OMNrVKkRONTVToV7EsUc

INSTALLING OF GEOPANDAS
"""

# Commented out IPython magic to ensure Python compatibility.
import geopandas as gpd
import matplotlib.pyplot as plt
# %matplotlib inline

"""ADDING VECTOR DATA"""

municipality=gpd.read_file('/content/municipality.shp')

"""READING MATA DATA"""

len(municipality)

municipality.head()

municipality.geom_type

municipality.shape

municipality.crs

type(municipality)

"""MAP VISUALIZATION"""

municipality.plot()

municipality.boundary.plot()

municipality.plot(figsize=(10,10))

municipality.plot("PR_NAME",cmap='magma',legend=True)

ax=municipality.plot("PR_NAME",cmap='magma',legend=True,figsize=(10,10))
ax.set_axis_off()

"""WRITING DATA"""

abc=gpd.read_file('/content/municipality.shp')

abc.to_file('/content/drive/MyDrive/GEO SPATIAL ANALYSIS/output/municipality.shp')

abc.to_file('/content/drive/MyDrive/GEO SPATIAL ANALYSIS/outputmunicipality.geojson',driver='GeoJSON',encoding='utf-8')

abc.to_file('/content/drive/MyDrive/GEO SPATIAL ANALYSIS/outputmunicipality.gPKG',driver='GPKG',layer="palika",encoding='utf-8')

"""WORKING WITH ATTRIBUTE"""

rupandehi=municipality[municipality['DISTRICT']=="RUPANDEHI"]

rupandehi.plot()

rupandehi.head()

len(rupandehi)

rupandehi.shape

rupandehi.plot("PALIKA",cmap="magma")

muncipality1=gpd.read_file('/content/municipality.shp')

muncipality1.head()

muncipality1['area']=0

muncipality_crs=muncipality1.to_crs(epsg=32645)

muncipality_crs['area']=muncipality_crs.geometry.area/10**6

muncipality_crs.head()

muncipality_crs.plot('area',legend=True)

from shapely.geometry import Point, LineString , Polygon

#creating a geometric object
point=Point(1,1)
line=LineString([(0,0),(5,9),(10,8)])
poly=line.buffer(1)

point

line

poly

point.within(poly)

point1=Point(1,7)
point1.within(poly)

poly.contains(point1)

gs=gpd.GeoSeries([Point(-10,15),Point(10,2),Point(-5,16)])
gs

gs.plot(marker="*",color='red',markersize=100,figsize=(4,4))

palpa=muncipality[muncipality['DISTRICT']=='PALPA']

palpa.plot()

ax=rupandehi.plot(figsize=(10,10))
palpa.plot(ax==ax)

!pip install folium matplotlib mapclassify

import mapclassify
import folium
import matplotlib

rupandehi.explore()

rupandehi.explore(column='PALIKA',cmap='magma')

